# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/zodiac/Projects/net

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/zodiac/Projects/net

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zodiac/Projects/net/CMakeFiles /home/zodiac/Projects/net/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zodiac/Projects/net/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named net_test

# Build rule for target.
net_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 net_test
.PHONY : net_test

# fast build rule for target.
net_test/fast:
	$(MAKE) -f CMakeFiles/net_test.dir/build.make CMakeFiles/net_test.dir/build
.PHONY : net_test/fast

test_main.o: test_main.cpp.o
.PHONY : test_main.o

# target to build an object file
test_main.cpp.o:
	$(MAKE) -f CMakeFiles/net_test.dir/build.make CMakeFiles/net_test.dir/test_main.cpp.o
.PHONY : test_main.cpp.o

test_main.i: test_main.cpp.i
.PHONY : test_main.i

# target to preprocess a source file
test_main.cpp.i:
	$(MAKE) -f CMakeFiles/net_test.dir/build.make CMakeFiles/net_test.dir/test_main.cpp.i
.PHONY : test_main.cpp.i

test_main.s: test_main.cpp.s
.PHONY : test_main.s

# target to generate assembly for a file
test_main.cpp.s:
	$(MAKE) -f CMakeFiles/net_test.dir/build.make CMakeFiles/net_test.dir/test_main.cpp.s
.PHONY : test_main.cpp.s

test_tcp.o: test_tcp.cpp.o
.PHONY : test_tcp.o

# target to build an object file
test_tcp.cpp.o:
	$(MAKE) -f CMakeFiles/net_test.dir/build.make CMakeFiles/net_test.dir/test_tcp.cpp.o
.PHONY : test_tcp.cpp.o

test_tcp.i: test_tcp.cpp.i
.PHONY : test_tcp.i

# target to preprocess a source file
test_tcp.cpp.i:
	$(MAKE) -f CMakeFiles/net_test.dir/build.make CMakeFiles/net_test.dir/test_tcp.cpp.i
.PHONY : test_tcp.cpp.i

test_tcp.s: test_tcp.cpp.s
.PHONY : test_tcp.s

# target to generate assembly for a file
test_tcp.cpp.s:
	$(MAKE) -f CMakeFiles/net_test.dir/build.make CMakeFiles/net_test.dir/test_tcp.cpp.s
.PHONY : test_tcp.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... net_test"
	@echo "... rebuild_cache"
	@echo "... test_main.o"
	@echo "... test_main.i"
	@echo "... test_main.s"
	@echo "... test_tcp.o"
	@echo "... test_tcp.i"
	@echo "... test_tcp.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

